USE healthcare_analytics;

-- Revenue Analysis

-- Calculate total revenue by treatment type

SELECT t.treatment_type, SUM(t.treatment_cost) AS "Total_Revenue"
FROM treatments t 
JOIN appointments a 
ON a.appointment_id = t.appointment_id
WHERE a.status = "completed"
GROUP BY t.treatment_type;

-- Find total number of treatments per hospital
SELECT
    h.hospital_name,
    COUNT(t.treatment_id) AS total_treatments
FROM treatments t
INNER JOIN appointments a ON t.appointment_id = a.appointment_id
INNER JOIN doctors d      ON a.doctor_id      = d.doctor_id
INNER JOIN hospitals h    ON d.hospital_id    = h.hospital_id
WHERE a.status = 'completed'
GROUP BY h.hospital_id, h.hospital_name
ORDER BY total_treatments DESC;

-- Identify top 5 treatments by revenue
SELECT t.treatment_id, t.treatment_type, t.treatment_cost
FROM treatments t 
JOIN appointments a
ON t.appointment_id = a.appointment_id
WHERE a.status = 'completed'
LIMIT 5;

-- Find average treatment cost per specialization
SELECT d.specialization, AVG(treatment_cost) AS 'Average Treatment Cost'
FROM doctors d
JOIN appointments a 
ON d.doctor_id = a.doctor_id
JOIN treatments t 
ON a.appointment_id = t.appointment_id
WHERE a.status = 'completed'
GROUP BY d.specialization;

-- -----------------------------------------------------------------------------------------------------------------------

-- Patient Segmentation

-- Calculate recency, frequency, and monetary value for each patient
SELECT p.patient_id, p.patient_name,
DATEDIFF(CURRENT_DATE, MAX(a.appointment_date)) AS 'recency_days',
COUNT(DISTINCT a.appointment_id) AS 'Frequency',
SUM(t.treatment_cost) AS 'Monetary_Value' 	
FROM patients p 
JOIN appointments a ON p.patient_id = a.patient_id
JOIN treatments t ON a.appointment_id = t.appointment_id 
WHERE a.status = 'completed'
GROUP BY p.patient_id, p.patient_name
ORDER BY monetary_value DESC;

-- Assign RFM scores using NTILE
WITH Raw_RFM AS (
SELECT p.patient_id, p.patient_name,
DATEDIFF(CURRENT_DATE, MAX(a.appointment_date)) AS 'recency_days',
COUNT(DISTINCT a.appointment_id) AS 'Frequency',
SUM(t.treatment_cost) AS 'Monetary_Value' 	
FROM patients p 
JOIN appointments a ON p.patient_id = a.patient_id
JOIN treatments t ON a.appointment_id = t.appointment_id 
WHERE a.status = 'completed'
GROUP BY p.patient_id, p.patient_name
ORDER BY monetary_value DESC
)
SELECT patient_id, patient_name,
NTILE(5) OVER(ORDER BY Recency_days DESC) AS 'R_score',
NTILE(5) OVER(ORDER BY Frequency ASC) AS 'F_score',
NTILE(5) OVER(ORDER BY Monetary_Value ASC) AS 'M_score'
FROM Raw_RFM;

-- Identify top 10 high-value patients

WITH Rfm_Scores AS(
WITH Raw_RFM AS (
SELECT p.patient_id, p.patient_name,
DATEDIFF(CURRENT_DATE, MAX(a.appointment_date)) AS 'recency_days',
COUNT(DISTINCT a.appointment_id) AS 'Frequency',
SUM(t.treatment_cost) AS 'Monetary_Value' 	
FROM patients p 
JOIN appointments a ON p.patient_id = a.patient_id
JOIN treatments t ON a.appointment_id = t.appointment_id 
WHERE a.status = 'completed'
GROUP BY p.patient_id, p.patient_name
ORDER BY monetary_value DESC
)
SELECT patient_id, patient_name,
NTILE(5) OVER(ORDER BY Recency_days DESC) AS 'R_score',
NTILE(5) OVER(ORDER BY Frequency ASC) AS 'F_score',
NTILE(5) OVER(ORDER BY Monetary_Value ASC) AS 'M_score'
FROM Raw_RFM
)
SELECT patient_id, patient_name, R_score, F_score, M_score
FROM Rfm_scores
WHERE R_score = 5 AND F_score = 5 AND M_score = 5;

-- --------------------------------------------------------------------------------------------------------------------------------------------------
-- Doctor Performance

-- Calculate revenue generated by each doctor
SELECT d.doctor_id, d.doctor_name, SUM(t.treatment_cost) AS 'Revenue'
FROM doctors d 
JOIN appointments a 
ON d.doctor_id = a.doctor_id
JOIN treatments t 
ON a.appointment_id = t.appointment_id 
WHERE a.status = 'completed'
GROUP BY d.doctor_id, d.doctor_name
ORDER BY SUM(t.treatment_cost);

-- Find average rating per doctor

SELECT d.doctor_id, d.doctor_name, AVG(r.rating) AS 'Average_Rating'
FROM doctors d 
JOIN appointments a 
ON d.doctor_id = a.doctor_id 
JOIN reviews r 
ON a.appointment_id = r.appointment_id
WHERE a.status = 'completed'
GROUP BY d.doctor_id, d.doctor_name;

-- Rank doctors within each hospital (review this again)
SELECT d.doctor_id, d.doctor_name, h.hospital_name, AVG(r.rating) AS 'Average_Rating'
FROM hospitals h 
JOIN doctors d 
ON h.hospital_id = d.hospital_id
JOIN appointments a 
ON d.doctor_id = a.doctor_id 
JOIN reviews r 
ON a.appointment_id = r.appointment_id
WHERE a.status = 'completed'
GROUP BY d.doctor_id, d.doctor_name, h.hospital_name
ORDER BY h.hospital_name, Average_Rating;

-- -----------------------------------------------------------------------------------------------------------------

-- Hospital Analysis

-- Calculate total revenue per hospital

SELECT h.hospital_id, h.hospital_name, SUM(t.treatment_cost) AS 'Total_Revenue'
FROM hospitals h 
JOIN doctors d 
ON h.hospital_id = d.hospital_id 
JOIN appointments a 
ON d.doctor_id = a.doctor_id
JOIN treatments t 
ON a.appointment_id = t.appointment_id
WHERE a.status = 'completed'
GROUP BY h.hospital_id, h.hospital_name;

-- Compare hospitals within each state
SELECT h.hospital_id, h.hospital_name, h.state, SUM(t.treatment_cost) AS 'Total_Revenue'
FROM hospitals h 
JOIN doctors d 
ON h.hospital_id = d.hospital_id 
JOIN appointments a 
ON d.doctor_id = a.doctor_id
JOIN treatments t 
ON a.appointment_id = t.appointment_id
WHERE a.status = 'completed'
GROUP BY h.hospital_id, h.hospital_name, h.state;

-- Identify top hospital in each state
